### ISSUE TITLE
护身符系统

### ISSUE THREAD

**Issue by vitsumoc** [najoast/wow_forum#32]
护身符是一种物品，唯一，获取绑定，不可装备，不可出售。

护身符有职业要求，每个职业只能获取自己对应职业的护身符。

护身符只要放在玩家的包裹中即可产生效果，无需装备，多个护身符的效果可以共同生效。

护身符的存在都是对技能效果产生直接影响，而非对数值产生影响。

目前考虑的护身符设计：
战士： 巨兽之爪护符：“当你打出猛击后，立即取消你旋风斩技能的冷却时间”
法师： 双枪护符： “当你打出炎爆术后，立即取消你的炎爆术冷却时间，你的下一个炎爆术瞬发且不耗蓝，此炎爆术不会触发双枪效果”
诸如此类，各职业各天赋的护身符要分别设计。

护身符物品模板可以考虑直接修改数据库创建，护身符的战斗代码逻辑不知道能不能用LUA实现，如果能用LUA的话会简单一些。

**Comment by ZhanKC** [comment]
能不能做采矿脚本

**Comment by gawangjing-0317** [comment]
消失几个月了，是不是搬家了

**Comment by najoast** [comment]
没有，工作忙，暂时停更了。
