### ISSUE TITLE
lua仓库取消了是吗？

### ISSUE THREAD

**Issue by Zilanbo** [najoast/wow_forum#33]
在另一个帖子里找到了在线涨经验的lua代码，超级炉石和随身商人没找到，可以分享一下吗？

**Comment by vitsumoc** [comment]
超级炉石现在网上也能找到，你随便搜搜就有

老版本的随身商人有点bug，需要改sql语句，还有就是不同玩家购买不同类别商品时有问题，需要自己修一下

**Comment by Zilanbo** [comment]
> 超级炉石现在网上也能找到，你随便搜搜就有
> 
> 老版本的随身商人有点bug，需要改sql语句，还有就是不同玩家购买不同类别商品时有问题，需要自己修一下

好的，谢谢

**Comment by najoast** [comment]
恢复了 https://github.com/najoast/eluna_scripts
